### ISSUE TITLE
Help with Oolite and OpenWRT

### ISSUE THREAD

**Issue by charleswhchan** [ooioe/OoliteV1trunk#1]
Hello,

We have a small batch of Oolite devices for development. Recently, we tried to take one and update the factory firmware to "Barrier Breaker", based on instructions provided from the OpenWRT project (http://wiki.openwrt.org/toh/oolite/oolitev1). Using the openwrt-ar71xx-generic-oolite-squashfs-sysupgrade.bin package from https://downloads.openwrt.org/barrier_breaker/14.07-rc3/ar71xx/generic/.

However, upon restarting the system, we find that the USB port is not working, it appears the bus is not powered. When we plug in a bluetooth/flash drive/mouse, there is no light from the device. We want to upgrade to "Barrier Breaker" in order to take advantage of the newer bluez libraries.

So a couple of questions:
1. What is the support status of Oolite with the official OpenWRT binary? Are the patches merged into the official OpenWRT trunk? Or is there an alternate firmware to use instead? 
1. Are there additional steps required to enable the USB port with barrier breaker?
2. Where is the factory image? How can we restore the device to the original firmware.

Thank you for your assistance.
Charles

**Comment by ooioe** [comment]
hi,friends

```
  thanks for you email

  1&2:  facotry firmware at http://www.ooiot.com/oolitev1/openwrt/firmware

           GPIO18 defined for USB power switch

           and dev-board's schematic and reference files : http://www.ooiot.com/oolitev1/openwrt/reference%20board/

    btw，how can I send you a email?
```

**Comment by charleswhchan** [comment]
Hello,

Thank you!!

We are now able to get the USB working by following instructions from http://elinux.org/GPIO

```
cd /sys/class/gpio
echo 18 > export

cd /sys/class/gpio/gpio18
echo "out" > direction
echo 1 > value
```

Do you know how to save these settings to enable the settings on startup?

Any chance you can push this change and enabled it by default into the official OpenWRT (barrier breaker, chaos calmer, etc)? That would be wonderful and support a collection of devices used by the community.
